### ISSUE TITLE
logs added directly to the root logger making it harder to mute or control

### ISSUE THREAD

**Issue by riqiang-dp** [NVIDIA/NeMo-text-processing#119]
I believe this line here adds the logs directly to the root logger. Shouldn't it be logger.info instead of logging.info?

I'm using nemo-text-processing within another process and want to change the log level just with nemo-text-processing

https://github.com/NVIDIA/NeMo-text-processing/blob/0ded21aad55c68189d1695c64c2b8e9fef71ef00/nemo_text_processing/text_normalization/data_loader_utils.py#L347

**Comment by ekmb** [comment]
Fixed in https://github.com/NVIDIA/NeMo-text-processing/pull/118
