### ISSUE TITLE
how to run Zh context-aware TN 

### ISSUE THREAD

**Issue by aixingxy** [NVIDIA/NeMo-text-processing#139]
I successfully run the EN context-aware TN in the documentation. 

[wfst_lm_rescoring.py](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/text_normalization/wfst/wfst_text_normalization.html#quick-start-guide)

I create a file "ChineseTN.json"
```
{"text": "全国有211所211高校。", "gt_normalized": "全国有二百一十一所二幺幺高校。"}
```
Change the `data` and `lang` args in `wfst_lm_rescoring.py`  , I got the following error.
```
FileNotFoundError: [Errno 2] No such file or directory: '/**/NeMo-text-processing/nemo_text_processing/text_normalization/zh/data/measure/measurements.tsv'
```
how to solve this problem?

**Comment by ekmb** [comment]
Context-aware TN supports only English at the moment. https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/text_normalization/wfst/wfst_text_normalization.html#language-support-matrix

**Comment by aixingxy** [comment]
> Context-aware TN supports only English at the moment. https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/text_normalization/wfst/wfst_text_normalization.html#language-support-matrix

got it thank you
