### ISSUE TITLE
russian inverse text normalization is broke for numbers less than 10

### ISSUE THREAD

**Issue by vikcost** [NVIDIA/NeMo-text-processing#146]
Example:
```
from nemo_text_processing.inverse_text_normalization.inverse_normalize import InverseNormalizer
inv_norm = InverseNormalizer(lang='ru')

inv_norm.normalize('тридцать')
'30' 

inv_norm.normalize('три')
'три' # expected '3'

inv_norm.normalize('два')
'два' expected '2'
```

**Comment by ekmb** [comment]
This is intended behaviour to keep numbers <10 in their spoken form, you can comment out https://github.com/NVIDIA/NeMo-text-processing/blob/main/nemo_text_processing/inverse_text_normalization/ru/taggers/cardinal.py#L44 to avoid this.

**Comment by vikcost** [comment]
Thanks, I figured this too.
I wonder what's the intended use case for such a behavior?

One might expect that (inverse)normalization has a universal behavior across the languages.

**Comment by vikcost** [comment]
nevertheless, even with a suggested change, inverse normalization of ordinals is error-prone.
```
третий год -> третий год # expected '3-й год'
тридцать третий час -> 33 час # expected '33-й час'
```

**Comment by ekmb** [comment]
> Thanks, I figured this too. I wonder what's the intended use case for such a behavior?
> 
> One might expect that (inverse)normalization has a universal behavior across the languages.

The motivation is to avoid normalization for cases like `one of us`.

**Comment by Hannan-Komari** [comment]
> Collaborator

There is such a problem in English. What to do to resolve it in English?

**Comment by vikcost** [comment]
@ekmb thanks for the example. 

Intuitively it should be possible to build a graph that accounts for cases as "one of us" and returns identity without any inverse-normalization.

On the other hand, it's is totally fine to expect the following "one of us" -> "1 of us".

**Comment by ekmb** [comment]
> > Collaborator
> 
> There is such a problem in English. What to do to resolve it in English?

You'd need to replace [this line](https://github.com/NVIDIA/NeMo-text-processing/blob/main/nemo_text_processing/inverse_text_normalization/en/taggers/cardinal.py#L234) with `self.graph = graph`
