### ISSUE TITLE
Supported languages not listed in args

### ISSUE THREAD

**Issue by Jorjeous** [NVIDIA/NeMo-text-processing#154]
https://github.com/NVIDIA/NeMo-text-processing/blob/0894c7012b21a62c28049083fb9ccd4152e8b235/nemo_text_processing/text_normalization/normalize_with_audio.py#L424

**Comment by ekmb** [comment]
Only the listed languages support audio-based normalization, i.e. their grammar includes additional normalization options. You might not see any non-deterministic options for unsupported languages or a limited number of options. [Language support matrix](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/nlp/text_normalization/wfst/wfst_text_normalization.html)
