### ISSUE TITLE
malloc error on initialization of inverse normalizer

### ISSUE THREAD

**Issue by hannan72** [NVIDIA/NeMo-text-processing#159]
In the initialization of inverse normalizer for English language, sometimes the code crashed with the following error at the initialization:
```malloc(): unaligned tcache chunk detected```
I traced the code and found this occasional error occured in the importing some modules from `pynini` package in `nemo_text_processing/text_normalization/en/graph_utils.py` lines 23 to 25:
![image](https://github.com/NVIDIA/NeMo-text-processing/assets/8229163/5f71feea-80bb-4b6a-9316-b8515e3241cf)

I fixed this issue by updating `pynini` to version 2.1.6, however its version in requirements file is explicitly set to 2.1.5 and this version seems to be reason of such crash.

I think the pynini version in `requirements/requirements.txt` file should be updated to 2.1.6

- OS: Ubuntu 22.04 
- HW: CPU
- python 3.10

**Comment by anand-nv** [comment]
We haven't been able to reproduce this. Have you tried this on another machine?
