### ISSUE TITLE
French normalizer crashes

### ISSUE THREAD

**Issue by lbehringer** [NVIDIA/NeMo-text-processing#163]
**Describe the bug**

Instantiating a `Normalizer` object with `lang` set to `"fr"` leads to a crash after waiting for 2-3 min.

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.
```
>>> from nemo_text_processing.text_normalization import Normalizer
>>> norm = Normalizer(input_case="cased", lang="fr")
 NeMo-text-processing :: INFO     :: Creating ClassifyFst grammars. This might take some time...
Killed
```

**Expected behavior**

A Normalizer object for normalizing French text would be instantiated.

**Environment overview (please complete the following information)**

 - Environment location: local
 - Method of NeMo install: pip install nemo_text_processing (I tried releases 0.2.2rc0 and 0.3.0rc0)

**Environment details**

- OS version: Windows 10.0.19045 (using WSL: Linux version 5.15.146.1-microsoft-standard-WSL2)
- PyTorch version: 2.1.2
- Python version: 3.10.13

**Additional context**

It works fine for other languages (English, Italian, German, Spanish).

**Comment by ekmb** [comment]
@mgrafu could you take a look please?

**Comment by mgrafu** [comment]
We tried replicating this issue, but cannot replicate. The normalizer object is instantiated correctly on our end. You could try using pynini==2.1.5

**Comment by anand-nv** [comment]
@lbehringer you may not have enough memory in your WSL environment. Assigning additional memory would resolve this issue.
