### ISSUE TITLE
cherry-pick https://github.com/NVIDIA/NeMo/pull/5960

### ISSUE THREAD

**Issue by XuesongYang** [NVIDIA/NeMo-text-processing#43]
Just realized that the PR https://github.com/NVIDIA/NeMo/pull/5960 should be cherry-picked to this repo because all TN-related codes have been removed before that PR.

**Comment by yzhang123** [comment]
i already updated this repo, still thank you for the notice.

**Comment by yzhang123** [comment]
@ekmb deleted the wfst text normalization documentation from NeMo doc, so now we don't have docs

**Comment by yzhang123** [comment]
https://github.com/NVIDIA/NeMo/pull/6041
