### ISSUE TITLE
German TN: normalized numbers wrongly include spaces

### ISSUE THREAD

**Issue by eginhard** [NVIDIA/NeMo-text-processing#64]
**Describe the bug**

In German, numbers are currently normalized with spaces between each digit and unit, although these should normally be written without spaces. In TTS systems, this leads to unnatural pauses in the output.

**Steps/Code to reproduce bug**

1. Normalize "18940722"
2. Output is "achtzehn millionen neun hundert vierzig tausend sieben hundert zwei und zwanzig", see https://github.com/NVIDIA/NeMo-text-processing/blob/9afbaf20c569ed41567988956e0e90dc913dd516/tests/nemo_text_processing/de/data_text_normalization/test_cases_cardinal.txt#L48

**Expected behavior**

Output should be "achtzehn millionen neunhundertvierzigtausendsiebenhundertzweiundzwanzig" (spaces are introduced for millions and above).

**Environment details**

NVIDIA NeMo Text Processing 0.1.7rc0

**Comment by yzhang123** [comment]
@eginhard thanks for addressing this! We are aware of this. for our initial German version we did not tackle this feature. However, if you want this for your tts model to adjust pauses based on space, be aware that when pronouncing neunhundertvierzigtausendsiebenhundertzweiundzwanzig , there are short pauses between neunhundert, vierzigtausend,
